// Auto-generated product database
export const allProducts = [
  {
    "id": "1",
    "name": "Organic Apples",
    "price": 45,
    "description": "Fresh organic apples sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-apples.jpg",
    "category": "Fruits",
    "stock": 104,
    rating: 4.9,
    "reviews": 58,
    "organic": true,
    "featured": true,
    "shopId": "4",
    "images": ["/images/products/organic-apples.jpg"]
  },
  {
    "id": "4",
    "name": "Organic Mangoes",
    "price": 65,
    "description": "Fresh organic mangoes sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-mangoes.jpg",
    "category": "Fruits",
    "stock": 111,
    rating: 3.6,
    "reviews": 23,
    "organic": true,
    "featured": false,
    "shopId": "1",
    "images": ["/images/products/organic-mangoes.jpg"]
  },
  {
    "id": "16",
    "name": "Organic Spinach",
    "price": 25,
    "description": "Fresh organic spinach sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-spinach.jpg",
    "category": "Vegetables",
    "stock": 49,
    rating: 4.2,
    "reviews": 192,
    "organic": true,
    "featured": false,
    "shopId": "1",
    "images": ["/images/products/organic-spinach.jpg"]
  },
  {
    "id": "19",
    "name": "Organic Carrots",
    "price": 40,
    "description": "Fresh organic carrots sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-carrots.jpg",
    "category": "Vegetables",
    "stock": 112,
    rating: 3.7,
    "reviews": 124,
    "organic": true,
    "featured": false,
    "shopId": "4",
    "images": ["/images/products/organic-carrots.jpg"]
  },
  {
    "id": "32",
    "name": "Organic Rice",
    "price": 35,
    "description": "Fresh organic rice sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-rice.jpg",
    "category": "Grains",
    "stock": 100,
    rating: 4.2,
    "reviews": 15,
    "organic": true,
    "featured": false,
    "shopId": "1",
    "images": ["/images/products/organic-rice.jpg"]
  },
  {
    "id": "37",
    "name": "Organic Oats",
    "price": 42,
    "description": "Fresh organic oats sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-oats.jpg",
    "category": "Grains",
    "stock": 79,
    rating: 4.1,
    "reviews": 40,
    "organic": true,
    "featured": false,
    "shopId": "3",
    "images": ["/images/products/organic-oats.jpg"]
  },
  {
    "id": "43",
    "name": "Organic Toor Dal",
    "price": 65,
    "description": "Fresh organic toor dal sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-toor-dal.jpg",
    "category": "Pulses",
    "stock": 51,
    rating: 4.7,
    "reviews": 70,
    "organic": true,
    "featured": true,
    "shopId": "1",
    "images": ["/images/products/organic-toor-dal.jpg"]
  },
  {
    "id": "48",
    "name": "Organic Rajma",
    "price": 55,
    "description": "Fresh organic rajma sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-rajma.jpg",
    "category": "Pulses",
    "stock": 52,
    rating: 4.5,
    "reviews": 62,
    "organic": true,
    "featured": true,
    "shopId": "1",
    "images": ["/images/products/organic-rajma.jpg"]
  },
  {
    "id": "52",
    "name": "Organic Almonds",
    "price": 120,
    "description": "Fresh organic almonds sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-almonds.jpg",
    "category": "Nuts",
    "stock": 84,
    rating: 4.6,
    "reviews": 171,
    "organic": true,
    "featured": false,
    "shopId": "1",
    "images": ["/images/products/organic-almonds.jpg"]
  },
  {
    "id": "56",
    "name": "Organic Pistachios",
    "price": 110,
    "description": "Fresh organic pistachios sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-pistachios.jpg",
    "category": "Nuts",
    "stock": 94,
    rating: 4.5,
    "reviews": 58,
    "organic": true,
    "featured": true,
    "shopId": "3",
    "images": ["/images/products/organic-pistachios.jpg"]
  },
  {
    "id": "57",
    "name": "Organic Chia Seeds",
    "price": 88,
    "description": "Fresh organic chia seeds sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-chia-seeds.jpg",
    "category": "Seeds",
    "stock": 28,
    rating: 4.9,
    "reviews": 190,
    "organic": true,
    "featured": false,
    "shopId": "2",
    "images": ["/images/products/organic-chia-seeds.jpg"]
  },
  {
    "id": "60",
    "name": "Organic Sesame Seeds",
    "price": 35,
    "description": "Fresh organic sesame seeds sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-sesame-seeds.jpg",
    "category": "Seeds",
    "stock": 28,
    rating: 4.5,
    "reviews": 25,
    "organic": true,
    "featured": false,
    "shopId": "4",
    "images": ["/images/products/organic-sesame-seeds.jpg"]
  },
  {
    "id": "62",
    "name": "Organic Coconut Oil",
    "price": 42,
    "description": "Fresh organic coconut oil sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-coconut-oil.jpg",
    "category": "Oils",
    "stock": 39,
    rating: 3.5,
    "reviews": 173,
    "organic": true,
    "featured": true,
    "shopId": "1",
    "images": ["/images/products/organic-coconut-oil.jpg"]
  },
  {
    "id": "64",
    "name": "Organic Mustard Oil",
    "price": 68,
    "description": "Fresh organic mustard oil sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-mustard-oil.jpg",
    "category": "Oils",
    "stock": 37,
    rating: 4.6,
    "reviews": 103,
    "organic": true,
    "featured": false,
    "shopId": "1",
    "images": ["/images/products/organic-mustard-oil.jpg"]
  },
  {
    "id": "72",
    "name": "Organic Milk",
    "price": 55,
    "description": "Fresh organic milk sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-milk.jpg",
    "category": "Dairy",
    "stock": 113,
    rating: 5.0,
    "reviews": 204,
    "organic": true,
    "featured": false,
    "shopId": "3",
    "images": ["/images/products/organic-milk.jpg"]
  },
  {
    "id": "70",
    "name": "Organic Cow Ghee",
    "price": 145,
    "description": "Fresh organic cow ghee sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-cow-ghee.jpg",
    "category": "Dairy",
    "stock": 60,
    rating: 3.8,
    "reviews": 65,
    "organic": true,
    "featured": false,
    "shopId": "3",
    "images": ["/images/products/organic-cow-ghee.jpg"]
  },
  {
    "id": "78",
    "name": "Organic Turmeric Powder",
    "price": 35,
    "description": "Fresh organic turmeric powder sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-turmeric-powder.jpg",
    "category": "Spices",
    "stock": 114,
    rating: 3.7,
    "reviews": 37,
    "organic": true,
    "featured": true,
    "shopId": "1",
    "images": ["/images/products/organic-turmeric-powder.jpg"]
  },
  {
    "id": "83",
    "name": "Organic Cinnamon",
    "price": 45,
    "description": "Fresh organic cinnamon sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-cinnamon.jpg",
    "category": "Spices",
    "stock": 97,
    rating: 4.6,
    "reviews": 176,
    "organic": true,
    "featured": false,
    "shopId": "2",
    "images": ["/images/products/organic-cinnamon.jpg"]
  },
  {
    "id": "101",
    "name": "Organic Green Tea",
    "price": 58,
    "description": "Fresh organic green tea sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-green-tea.jpg",
    "category": "Beverages",
    "stock": 85,
    rating: 4.7,
    "reviews": 142,
    "organic": true,
    "featured": true,
    "shopId": "1",
    "images": ["/images/products/organic-green-tea.jpg"]
  },
  {
    "id": "103",
    "name": "Organic Coffee Beans",
    "price": 42,
    "description": "Fresh organic coffee beans sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-coffee-beans.jpg",
    "category": "Beverages",
    "stock": 65,
    rating: 4.9,
    "reviews": 201,
    "organic": true,
    "featured": true,
    "shopId": "3",
    "images": ["/images/products/organic-coffee-beans.jpg"]
  },
  {
    "id": "104",
    "name": "Organic Honey",
    "price": 95,
    "description": "Fresh organic honey sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-honey.jpg",
    "category": "Pantry",
    "stock": 48,
    rating: 4.8,
    "reviews": 167,
    "organic": true,
    "featured": true,
    "shopId": "1",
    "images": ["/images/products/organic-honey.jpg"]
  },
  {
    "id": "105",
    "name": "Organic Jaggery",
    "price": 42,
    "description": "Fresh organic jaggery sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-jaggery.jpg",
    "category": "Pantry",
    "stock": 78,
    rating: 4.4,
    "reviews": 89,
    "organic": true,
    "featured": false,
    "shopId": "2",
    "images": ["/images/products/organic-jaggery.jpg"]
  },
  {
    "id": "108",
    "name": "Organic Dark Chocolate",
    "price": 38,
    "description": "Fresh organic dark chocolate sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-dark-chocolate.jpg",
    "category": "Snacks",
    "stock": 42,
    rating: 4.9,
    "reviews": 188,
    "organic": true,
    "featured": true,
    "shopId": "1",
    "images": ["/images/products/organic-dark-chocolate.jpg"]
  },
  {
    "id": "92",
    "name": "Organic Granola",
    "price": 75,
    "description": "Fresh organic granola sourced from certified organic farms. Premium quality guaranteed.",
    "image": "/images/products/organic-granola.jpg",
    "category": "Snacks",
    "stock": 98,
    rating: 5.0,
    "reviews": 49,
    "organic": true,
    "featured": true,
    "shopId": "2",
    "images": ["/images/products/organic-granola.jpg"]
  }
];
