export const tamilTranslations = {
  home: 'முகப்பு', products: 'தயாரிப்புகள்', cart: 'வண்டி', checkout: 'செக்அவுட்', login: 'உள்நுழைய', register: 'பதிவு',
  about: 'எங்களை பற்றி', contact: 'தொடர்பு', logout: 'வெளியேறு', dashboard: 'டாஷ்போர்டு', profile: 'சுயவிவரம்',
  addToCart: 'வண்டியில் சேர்', shopNow: 'இப்போது வாங்கு', viewDetails: 'விவரங்களைக் காண்க', placeOrder: 'ஆர்டர் செய்',
  proceedToCheckout: 'செக்அவுட்டுக்கு செல்', remove: 'அகற்று', update: 'புதுப்பி', save: 'சேமி', cancel: 'ரத்து',
  download: 'பதிவிறக்கு', track: 'கண்காணி', search: 'தேடு', filter: 'வடிகட்டு', sort: 'வரிசைப்படுத்து',
  total: 'மொத்தம்', subtotal: 'துணை மொத்தம்', quantity: 'அளவு', price: 'விலை', name: 'பெயர்', email: 'மின்னஞ்சல்',
  phone: 'தொலைபேசி', address: 'முகவரி', city: 'நகரம்', state: 'மாநிலம்', zipCode: 'அஞ்சல் குறியீடு', country: 'நாடு',
  shippingAddress: 'அனுப்பும் முகவரி', paymentMethod: 'கட்டண முறை', orderSummary: 'ஆர்டர் சுருக்கம்',
  deliveryCharges: 'விநியோக கட்டணம்', tax: 'வரி', cashOnDelivery: 'பணம் செலுத்தி பெறுதல்',
  organicFood: 'இயற்கை உணவு', freshOrganic: 'புதிய இயற்கை உணவு',
  farmFresh: 'உங்கள் வீட்டு வாசலுக்கு புதிய இயற்கை தயாரிப்புகள்',
  whyChooseUs: 'எங்களை ஏன் தேர்வு செய்ய வேண்டும்', certified: '100% இயற்கை', fastDelivery: 'விரைவான விநியோகம்',
  bestQuality: 'சிறந்த தரம்', easyShopping: 'எளிதான ஷாப்பிங்',
  myOrders: 'எனது ஆர்டர்கள்', orderHistory: 'ஆர்டர் வரலாறு', totalOrders: 'மொத்த ஆர்டர்கள்', totalSpent: 'மொத்த செலவு',
  recentOrders: 'சமீபத்திய ஆர்டர்கள்', noOrders: 'இன்னும் ஆர்டர்கள் இல்லை', startShopping: 'ஷாப்பிங் தொடங்கு',
  orderId: 'ஆர்டர் ஐடி', orderDate: 'ஆர்டர் தேதி', deliveryDate: 'விநியோக தேதி', trackingNumber: 'கண்காணிப்பு எண்',
  orderStatus: 'ஆர்டர் நிலை', confirmed: 'உறுதிப்படுத்தப்பட்டது', shipped: 'அனுப்பப்பட்டது', delivered: 'வழங்கப்பட்டது',
  downloadInvoice: 'விலைப்பட்டியல் பதிவிறக்கு', trackOrder: 'ஆர்டரைக் கண்காணி', expectedDelivery: 'எதிர்பார்க்கப்படும் விநியோகம்',
  category: 'வகை', rating: 'மதிப்பீடு', reviews: 'விமர்சனங்கள்', inStock: 'கையிருப்பில்', outOfStock: 'கையிருப்பில் இல்லை',
  welcomeBack: 'மீண்டும் வரவேற்கிறோம்', thankYou: 'நன்றி', orderPlaced: 'ஆர்டர் வெற்றிகரமாக வைக்கப்பட்டது',
  addedToCart: 'வண்டியில் சேர்க்கப்பட்டது', removedFromCart: 'வண்டியிலிருந்து அகற்றப்பட்டது', cartEmpty: 'உங்கள் வண்டி காலியாக உள்ளது',
  fruits: 'பழங்கள்', vegetables: 'காய்கறிகள்', dairy: 'பால் பொருட்கள்', bakery: 'பேக்கரி', pantry: 'சமையலறை', grains: 'தானியங்கள்',
  quickLinks: 'விரைவு இணைப்புகள்', customerService: 'வாடிக்கையாளர் சேவை', followUs: 'எங்களைப் பின்தொடரவும்',
  allRightsReserved: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை', privacyPolicy: 'தனியுரிமை கொள்கை', termsOfService: 'சேவை விதிமுறைகள்',
  wishlist: 'விருப்பப்பட்டியல்', addToWishlist: 'விருப்பப்பட்டியலில் சேர்', removeFromWishlist: 'விருப்பப்பட்டியலிலிருந்து அகற்று',
}

export const teluguTranslations = {
  home: 'హోమ్', products: 'ఉత్పత్తులు', cart: 'కార్ట్', checkout: 'చెక్అవుట్', login: 'లాగిన్', register: 'రిజిస్టర్',
  about: 'మా గురించి', contact: 'సంప్రదించండి', logout: 'లాగౌట్', dashboard: 'డాష్‌బోర్డ్', profile: 'ప్రొఫైల్',
  addToCart: 'కార్ట్‌కు జోడించు', shopNow: 'ఇప్పుడు కొనుగోలు చేయండి', viewDetails: 'వివరాలు చూడండి', placeOrder: 'ఆర్డర్ చేయండి',
  proceedToCheckout: 'చెక్అవుట్‌కు వెళ్ళండి', remove: 'తొలగించు', update: 'నవీకరించు', save: 'సేవ్ చేయి', cancel: 'రద్దు చేయి',
  download: 'డౌన్‌లోడ్', track: 'ట్రాక్', search: 'వెతకండి', filter: 'ఫిల్టర్', sort: 'క్రమబద్ధీకరించు',
  total: 'మొత్తం', subtotal: 'ఉప మొత్తం', quantity: 'పరిమాణం', price: 'ధర', name: 'పేరు', email: 'ఇమెయిల్',
  phone: 'ఫోన్', address: 'చిరునామా', city: 'నగరం', state: 'రాష్ట్రం', zipCode: 'పిన్ కోడ్', country: 'దేశం',
  shippingAddress: 'షిప్పింగ్ చిరునామా', paymentMethod: 'చెల్లింపు పద్ధతి', orderSummary: 'ఆర్డర్ సారాంశం',
  deliveryCharges: 'డెలివరీ ఛార్జీలు', tax: 'పన్ను', cashOnDelivery: 'క్యాష్ ఆన్ డెలివరీ',
  organicFood: 'సేంద్రీయ ఆహారం', freshOrganic: 'తాజా సేంద్రీయ ఆహారం',
  farmFresh: 'మీ ఇంటి వద్దకు తాజా సేంద్రీయ ఉత్పత్తులు',
  whyChooseUs: 'మమ్మల్ని ఎందుకు ఎంచుకోవాలి', certified: '100% సేంద్రీయ', fastDelivery: 'వేగవంతమైన డెలివరీ',
  bestQuality: 'ఉత్తమ నాణ్యత', easyShopping: 'సులభమైన షాపింగ్',
  myOrders: 'నా ఆర్డర్లు', orderHistory: 'ఆర్డర్ చరిత్ర', totalOrders: 'మొత్తం ఆర్డర్లు', totalSpent: 'మొత్తం ఖర్చు',
  recentOrders: 'ఇటీవలి ఆర్డర్లు', noOrders: 'ఇంకా ఆర్డర్లు లేవు', startShopping: 'షాపింగ్ ప్రారంభించండి',
  orderId: 'ఆర్డర్ ఐడి', orderDate: 'ఆర్డర్ తేదీ', deliveryDate: 'డెలివరీ తేదీ', trackingNumber: 'ట్రాకింగ్ నంబర్',
  orderStatus: 'ఆర్డర్ స్థితి', confirmed: 'నిర్ధారించబడింది', shipped: 'పంపబడింది', delivered: 'డెలివరీ చేయబడింది',
  downloadInvoice: 'ఇన్‌వాయిస్ డౌన్‌లోడ్ చేయండి', trackOrder: 'ఆర్డర్‌ను ట్రాక్ చేయండి', expectedDelivery: 'ఆశించిన డెలివరీ',
  category: 'వర్గం', rating: 'రేటింగ్', reviews: 'సమీక్షలు', inStock: 'స్టాక్‌లో ఉంది', outOfStock: 'స్టాక్ అయిపోయింది',
  welcomeBack: 'తిరిగి స్వాగతం', thankYou: 'ధన్యవాదాలు', orderPlaced: 'ఆర్డర్ విజయవంతంగా ఇవ్వబడింది',
  addedToCart: 'కార్ట్‌కు జోడించబడింది', removedFromCart: 'కార్ట్ నుండి తొలగించబడింది', cartEmpty: 'మీ కార్ట్ ఖాళీగా ఉంది',
  fruits: 'పండ్లు', vegetables: 'కూరగాయలు', dairy: 'పాల ఉత్పత్తులు', bakery: 'బేకరీ', pantry: 'ప్యాంట్రీ', grains: 'ధాన్యాలు',
  quickLinks: 'శీఘ్ర లింక్‌లు', customerService: 'కస్టమర్ సేవ', followUs: 'మమ్మల్ని అనుసరించండి',
  allRightsReserved: 'అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి', privacyPolicy: 'గోప్యతా విధానం', termsOfService: 'సేవా నిబంధనలు',
  wishlist: 'విష్‌లిస్ట్', addToWishlist: 'విష్‌లిస్ట్‌కు జోడించు', removeFromWishlist: 'విష్‌లిస్ట్ నుండి తొలగించు',
}
