export const bengaliTranslations = {
  home: 'হোম', products: 'পণ্য', cart: 'কার্ট', checkout: 'চেকআউট', login: 'লগইন', register: 'নিবন্ধন',
  about: 'আমাদের সম্পর্কে', contact: 'যোগাযোগ', logout: 'লগআউট', dashboard: 'ড্যাশবোর্ড', profile: 'প্রোফাইল',
  addToCart: 'কার্টে যোগ করুন', shopNow: 'এখনই কিনুন', viewDetails: 'বিস্তারিত দেখুন', placeOrder: 'অর্ডার করুন',
  proceedToCheckout: 'চেকআউটে যান', remove: 'সরান', update: 'আপডেট', save: 'সংরক্ষণ', cancel: 'বাতিল',
  download: 'ডাউনলোড', track: 'ট্র্যাক', search: 'খুঁজুন', filter: 'ফিল্টার', sort: 'সাজান',
  total: 'মোট', subtotal: 'উপমোট', quantity: 'পরিমাণ', price: 'মূল্য', name: 'নাম', email: 'ইমেইল',
  phone: 'ফোন', address: 'ঠিকানা', city: 'শহর', state: 'রাজ্য', zipCode: 'পিন কোড', country: 'দেশ',
  shippingAddress: 'শিপিং ঠিকানা', paymentMethod: 'পেমেন্ট পদ্ধতি', orderSummary: 'অর্ডার সারাংশ',
  deliveryCharges: 'ডেলিভারি চার্জ', tax: 'কর', cashOnDelivery: 'ক্যাশ অন ডেলিভারি',
  organicFood: 'জৈব খাদ্য', freshOrganic: 'তাজা জৈব খাদ্য',
  farmFresh: 'আপনার দোরগোড়ায় তাজা জৈব পণ্য',
  whyChooseUs: 'কেন আমাদের বেছে নেবেন', certified: '১০০% জৈব', fastDelivery: 'দ্রুত ডেলিভারি',
  bestQuality: 'সেরা মান', easyShopping: 'সহজ কেনাকাটা',
  myOrders: 'আমার অর্ডার', orderHistory: 'অর্ডার ইতিহাস', totalOrders: 'মোট অর্ডার', totalSpent: 'মোট খরচ',
  recentOrders: 'সাম্প্রতিক অর্ডার', noOrders: 'এখনও কোনো অর্ডার নেই', startShopping: 'কেনাকাটা শুরু করুন',
  orderId: 'অর্ডার আইডি', orderDate: 'অর্ডার তারিখ', deliveryDate: 'ডেলিভারি তারিখ', trackingNumber: 'ট্র্যাকিং নম্বর',
  orderStatus: 'অর্ডার স্ট্যাটাস', confirmed: 'নিশ্চিত', shipped: 'পাঠানো হয়েছে', delivered: 'ডেলিভার করা হয়েছে',
  downloadInvoice: 'চালান ডাউনলোড করুন', trackOrder: 'অর্ডার ট্র্যাক করুন', expectedDelivery: 'প্রত্যাশিত ডেলিভারি',
  category: 'বিভাগ', rating: 'রেটিং', reviews: 'পর্যালোচনা', inStock: 'স্টকে আছে', outOfStock: 'স্টকে নেই',
  welcomeBack: 'আবার স্বাগতম', thankYou: 'ধন্যবাদ', orderPlaced: 'অর্ডার সফলভাবে দেওয়া হয়েছে',
  addedToCart: 'কার্টে যোগ করা হয়েছে', removedFromCart: 'কার্ট থেকে সরানো হয়েছে', cartEmpty: 'আপনার কার্ট খালি',
  fruits: 'ফল', vegetables: 'সবজি', dairy: 'দুগ্ধজাত', bakery: 'বেকারি', pantry: 'প্যান্ট্রি', grains: 'শস্য',
  quickLinks: 'দ্রুত লিঙ্ক', customerService: 'গ্রাহক সেবা', followUs: 'আমাদের অনুসরণ করুন',
  allRightsReserved: 'সর্বস্বত্ব সংরক্ষিত', privacyPolicy: 'গোপনীয়তা নীতি', termsOfService: 'সেবার শর্তাবলী',
  wishlist: 'উইশলিস্ট', addToWishlist: 'উইশলিস্টে যোগ করুন', removeFromWishlist: 'উইশলিস্ট থেকে সরান',
}

export const marathiTranslations = {
  home: 'होम', products: 'उत्पादने', cart: 'कार्ट', checkout: 'चेकआउट', login: 'लॉगिन', register: 'नोंदणी',
  about: 'आमच्याबद्दल', contact: 'संपर्क', logout: 'लॉगआउट', dashboard: 'डॅशबोर्ड', profile: 'प्रोफाइल',
  addToCart: 'कार्टमध्ये जोडा', shopNow: 'आता खरेदी करा', viewDetails: 'तपशील पहा', placeOrder: 'ऑर्डर द्या',
  proceedToCheckout: 'चेकआउटवर जा', remove: 'काढा', update: 'अपडेट', save: 'जतन करा', cancel: 'रद्द करा',
  download: 'डाउनलोड', track: 'ट्रॅक', search: 'शोधा', filter: 'फिल्टर', sort: 'क्रमवारी',
  total: 'एकूण', subtotal: 'उपएकूण', quantity: 'प्रमाण', price: 'किंमत', name: 'नाव', email: 'ईमेल',
  phone: 'फोन', address: 'पत्ता', city: 'शहर', state: 'राज्य', zipCode: 'पिन कोड', country: 'देश',
  shippingAddress: 'शिपिंग पत्ता', paymentMethod: 'पेमेंट पद्धत', orderSummary: 'ऑर्डर सारांश',
  deliveryCharges: 'डिलिव्हरी शुल्क', tax: 'कर', cashOnDelivery: 'कॅश ऑन डिलिव्हरी',
  organicFood: 'सेंद्रिय अन्न', freshOrganic: 'ताजे सेंद्रिय अन्न',
  farmFresh: 'तुमच्या दारापर्यंत ताजी सेंद्रिय उत्पादने',
  whyChooseUs: 'आम्हाला का निवडावे', certified: '१००% सेंद्रिय', fastDelivery: 'जलद डिलिव्हरी',
  bestQuality: 'सर्वोत्तम गुणवत्ता', easyShopping: 'सोपी खरेदी',
  myOrders: 'माझे ऑर्डर', orderHistory: 'ऑर्डर इतिहास', totalOrders: 'एकूण ऑर्डर', totalSpent: 'एकूण खर्च',
  recentOrders: 'अलीकडील ऑर्डर', noOrders: 'अद्याप कोणतेही ऑर्डर नाहीत', startShopping: 'खरेदी सुरू करा',
  orderId: 'ऑर्डर आयडी', orderDate: 'ऑर्डर तारीख', deliveryDate: 'डिलिव्हरी तारीख', trackingNumber: 'ट्रॅकिंग नंबर',
  orderStatus: 'ऑर्डर स्थिती', confirmed: 'पुष्टी केली', shipped: 'पाठवले', delivered: 'वितरित केले',
  downloadInvoice: 'चलन डाउनलोड करा', trackOrder: 'ऑर्डर ट्रॅक करा', expectedDelivery: 'अपेक्षित डिलिव्हरी',
  category: 'श्रेणी', rating: 'रेटिंग', reviews: 'पुनरावलोकने', inStock: 'स्टॉकमध्ये', outOfStock: 'स्टॉक संपला',
  welcomeBack: 'परत स्वागत आहे', thankYou: 'धन्यवाद', orderPlaced: 'ऑर्डर यशस्वीरित्या दिली',
  addedToCart: 'कार्टमध्ये जोडले', removedFromCart: 'कार्टमधून काढले', cartEmpty: 'तुमची कार्ट रिकामी आहे',
  fruits: 'फळे', vegetables: 'भाज्या', dairy: 'दुग्धोत्पादने', bakery: 'बेकरी', pantry: 'पॅन्ट्री', grains: 'धान्य',
  quickLinks: 'द्रुत दुवे', customerService: 'ग्राहक सेवा', followUs: 'आम्हाला फॉलो करा',
  allRightsReserved: 'सर्व हक्क राखीव', privacyPolicy: 'गोपनीयता धोरण', termsOfService: 'सेवा अटी',
  wishlist: 'विशलिस्ट', addToWishlist: 'विशलिस्टमध्ये जोडा', removeFromWishlist: 'विशलिस्टमधून काढा',
}
